const getShortlist = (data, req, res) => {
  const { hostQuery } = data

  if (hostQuery.status) {
    res.status(hostQuery.status)
  }

  const success = {
    success: true,
    message: 'Done.',
    payload: {
      isPagedResult: false,
      pageNumber: null,
      nextPageAvailable: null,
      pageSize: null,
      totalRecords: null,
      items: [
        {
          guid: '1210a4b0-817f-4992-ab9b-367b439278ee',
          boatId: 11646,
          providerId: 4,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/1',
            name: 'KEFISO',
            model: 'Maxus 22 Prestige',
            type: 'Plachetnice',
            productionYear: 2017,
            berths: '6 (4+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 599,
            basePrice: 630,
            discountPercentage: 5,
          },
        },
        {
          guid: '786ee01e-883f-47d1-ad1a-dae0c5135b64',
          boatId: 60506,
          providerId: 1,
          status: 'preBookedByMe',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/2',
            name: 'KRETA',
            model: 'Maxus 24 Standard',
            type: 'Plachetnice',
            productionYear: 2014,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'Port ZHP',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 612,
            basePrice: 644,
            discountPercentage: 5,
          },
        },
        {
          guid: 'a2da2dad-af41-4afe-8de2-8cd0e04f3f74',
          boatId: 58678,
          providerId: 4,
          status: 'booked',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/3',
            name: 'Blue-Pi',
            model: 'Maxi 77',
            type: 'Plachetnice',
            productionYear: 1982,
            berths: '4',
            cabins: '1',
            heads: '0',
            company: 'Sail Stockholm',
            country: 'Croatia',
            countryCode: 'HR',
            marina: 'Komolac, ACI Marinca Dubrovnik',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 618,
            basePrice: 650,
            discountPercentage: 5,
          },
        },
        {
          guid: '139d5cef-7a81-45f8-b3d6-3cf909f88204',
          boatId: 60468,
          providerId: 1,
          status: 'preBooked',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/4',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-02-10',
            dateTo: '2018-02-17',
            price: 293,
            basePrice: 308,
            discountPercentage: 5,
          },
        },
        {
          guid: 'dda2cc49-cb85-43d7-8ab7-a50bf4108ecf',
          boatId: 60518,
          providerId: 1,
          status: 'inWaitingList',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/5',
            name: 'CORAL SEA',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2016,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 632,
            basePrice: 665,
            discountPercentage: 5,
          },
        },
        {
          guid: '13350df1-9bcb-42fa-837a-ee9df2783a2e',
          boatId: 60469,
          providerId: 1,
          status: 'expired',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/6',
            name: 'PAPARAPA 2',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2016,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'Port ZHP',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 645,
            basePrice: 679,
            discountPercentage: 5,
          },
        },
        {
          guid: 'afd73186-12a9-4563-bdf0-6038d74211ac',
          boatId: 49304,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/7',
            name: 'Gertrud',
            model: 'Other',
            type: 'Plachetnice',
            productionYear: 1978,
            berths: '2',
            cabins: '1',
            heads: null,
            company: 'mediamare yachtcharter',
            country: 'N�mecko',
            countryCode: 'DE',
            marina: 'Marina Kr�slin',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 656,
            basePrice: 690,
            discountPercentage: 5,
          },
        },
        {
          guid: '79160cbf-eb0e-4ce0-a38b-9300b83d573b',
          boatId: 60492,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/8',
            name: 'VISERYS',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'Port ZHP',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-faagkac3af71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/9',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-oo7ajah12f71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/10',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-akfh782aaf8e',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/11',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-aa23jac3af71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/12',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-ajhg828aa3aj',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/13',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-kkaj8ac3af71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/14',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-1j3kzac3af71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/15',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-flla2ac3af71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/16',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
        {
          guid: '61cdcb97-7121-414d-b0f0-aie72ac3af71',
          boatId: 60468,
          providerId: 1,
          status: 'available',
          preBookedUntil: null,
          booking: {
            image: '//satyr.io/256x256/17',
            name: 'TAMLIN',
            model: 'Maxus evo 24 Prestige',
            type: 'Plachetnice',
            productionYear: 2018,
            berths: '8 (6+2)',
            cabins: null,
            heads: null,
            company: 'Ahoj Czarter',
            country: 'Polsko',
            countryCode: 'PL',
            marina: 'PTTK Wilkasy',
            dateFrom: '2018-07-07',
            dateTo: '2018-07-14',
            price: 685,
            basePrice: 721,
            discountPercentage: 5,
          },
        },
      ],
    },
    modelErrors: null,
    exception: null,
  }

  if (res) {
    switch (res.statusCode) {
      case '200':
        return success
      case '400':
        return {
          success: false,
          message: 'Sorry, we could not get your boats',
        }
      case '500':
        return {
          success: false,
          message: '500 Internal Server Error',
        }
      default:
        return {
          payload: {
            isPagedResult: false,
            items: [],
          },
        }
    }
  }

  return success
}
module.exports = getShortlist
